USE [master]
GO

/****** Object:  Database [Restaurant]     ******/
CREATE DATABASE [Restaurant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Restaurant', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Restaurant.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Restaurant_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Restaurant_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Restaurant] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Restaurant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Restaurant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Restaurant] SET ARITHABORT OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Restaurant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Restaurant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Restaurant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Restaurant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Restaurant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Restaurant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Restaurant] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Restaurant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Restaurant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Restaurant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Restaurant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Restaurant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Restaurant] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Restaurant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Restaurant] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Restaurant] SET  MULTI_USER 
GO

ALTER DATABASE [Restaurant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Restaurant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Restaurant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Restaurant] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Restaurant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Restaurant] SET  READ_WRITE 
GO


