USE [Restaurant]
GO
/********************************INSERT INTO [dbo].[Content]*********************************************/
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(1 ,1 ,'BreakFast','https://images.pexels.com/photos/2635307/pexels-photo-2635307.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','',1 )
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(2 ,1 ,'Wine&Dine','https://images.pexels.com/photos/2878738/pexels-photo-2878738.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','',2 )
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(3 ,1 ,'Meal','https://images.pexels.com/photos/1199958/pexels-photo-1199958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','',3 )
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(4 ,2 ,'Bagel','https://images.pexels.com/photos/6492/food-breakfast-fork-bagel.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500','Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium minus ipsam magni obcaecati tenetur quidem quibusdam porro hic accusamus fugiat, cum sint placeat pariatur temporibus tempore esse doloribus ea minima facilis necessitatibus veniam maxime inventore. Dignissimos quas labore architecto cumque ad facilis facere, eius neque error aspernatur voluptate beatae deserunt magni voluptates? Ducimus omnis quia maxime debitis voluptatum? Facere repellat ab cumque, dicta voluptas odit odio tempore dolor quaerat sed. Cumque quasi doloremque corporis, in perferendis placeat facilis magni, dolorum et praesentium natus, atque porro sunt autem dolores maiores adipisci libero harum rerum fuga ducimus repellendus! Dolor fugit iusto veniam?.',1)
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(5 ,2 ,'Vegetarian Alternatives','https://images.pexels.com/photos/1234535/pexels-photo-1234535.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500','Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, pariatur dicta cupiditate expedita quia laborum ipsa sint beatae in rem quae itaque numquam doloremque est eaque debitis quis? Quibusdam dignissimos omnis impedit iusto voluptatum sit laboriosam minus assumenda sint? Provident necessitatibus excepturi ipsam blanditiis eum autem assumenda. Facere, explicabo, a officia deserunt ullam quasi voluptatem quibusdam repellendus corrupti modi sit aspernatur tenetur dolores aperiam obcaecati beatae in, autem dolor maiores reiciendis dolorem. Veritatis commodi provident pariatur quod vero voluptas architecto assumenda! Sint vero nisi quos iste neque ipsa incidunt deserunt ad, recusandae dolorem amet eum sit assumenda, id error laudantium?.',2)
INSERT INTO [dbo].[Content]([Id],[IdSection],[Title],[Image],[Description],[Order])VALUES(6 ,2 ,'Sandwich','https://images.pexels.com/photos/7390/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500','Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia dignissimos cumque temporibus sequi, maxime quasi quam labore velit ad soluta animi, inventore est totam aliquid pariatur eos. Sed animi quo veniam expedita perferendis eos adipisci aut. Esse magnam quae dolores dignissimos asperiores corrupti! Ipsam placeat facilis qui obcaecati maxime sunt tempore itaque nesciunt fuga quod dolorum, at recusandae, rerum est harum quo natus ex. Asperiores placeat cum ipsam, quae a cumque enim nobis praesentium quam illum sint, voluptatibus necessitatibus laboriosam quibusdam, animi ex obcaecati perspiciatis voluptas vel qui! Quis dolore, magni cupiditate iusto doloribus animi dolorem obcaecati quod. Ipsum, corporis?',3)
/********************************INSERT INTO [dbo].[Section]*********************************************/
INSERT INTO [dbo].[Section]([Id],[Title],[Description]) VALUES(1 ,'Menu','')
INSERT INTO [dbo].[Section]([Id],[Title],[Description]) VALUES(2 ,'Feed','')